apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-app-pod-restart-alerts
  namespace: monitoring
spec:
  groups:
    - name: node-app.pod.rules
      rules:
        - alert: NodeAppPodRestartingTooOften
          expr: |
            increase(
              kube_pod_container_status_restarts_total{
                namespace="node-app"
              }[5m]
            ) > 3
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Node-app pod restarting frequently"
            description: "Pod {{ $labels.pod }} in node-app namespace restarted more than 3 times in 5 minutes."
